---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-staging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lets-encrypt.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Chart.Name }}-{{ .Release.Name }}-staging
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-prod
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lets-encrypt.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Chart.Name }}-{{ .Release.Name }}-prod
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
